### ISSUE TITLE
project fails to build on ubuntu 20.04 using CLion 2020.3

### ISSUE THREAD

**Issue by ti8m-hic** [MarinaKalashina/CMake-Tutorial-sample#1]
When I clone the repo into CLion, it fails to build:

/snap/clion/137/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/claus/CLionProjects/CMake-Tutorial-sample
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /snap/clion/137/bin/cmake/linux/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR unit_test_framework)
Call Stack (most recent call first):
  /snap/clion/137/bin/cmake/linux/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  /snap/clion/137/bin/cmake/linux/share/cmake-3.17/Modules/FindBoost.cmake:2166 (find_package_handle_standard_args)
  test/CMakeLists.txt:4 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/claus/CLionProjects/CMake-Tutorial-sample/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Failed to reload]

This is the CLion version information:

CLion 2020.3
Build #CL-203.5981.166, built on December 1, 2020
...
Runtime version: 11.0.9+11-b1145.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1987M
Cores: 8
Registry: run.processes.with.pty=TRUE
Current Desktop: Budgie:GNOME

This is the Linux version information:

+ cat /proc/version
Linux version 5.4.0-58-generic (buildd@lcy01-amd64-004) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020

I am new to CMake, and know nothing about BOOST. Please advise how to best fix this.

**Comment by MarinaKalashina** [comment]
Hi, please make sure you have Boost installed on your machine https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu

**Comment by ti8m-hic** [comment]
Thanks, that worked for me. Details:

$ sudo apt-get install libboost-all-dev
...

Then restarted CLion (probably not necessary)
Then on tab CMake pressed refresh
Then rebuilt the project
Outcome works fine.
